--- #YAML:1.0
name: Posy
version: 0.10
author:
  - Kathryn Andersen
abstract: a website generator inspired by blosxom
license: perl
requires:
  CGI::Minimal: 0
  Data::Dumper: 0
  File::Find: 0
  File::Spec: 0
  File::stat: 0
  Getopt::ArgvFile: 1.09
  Getopt::Long: 2.34
  Pod::Usage: 0
  Storable: 0
build_requires:
  Test::More: 0
provides:
  Posy:
    file: lib/Posy.pm
    version: 0.10
  Posy::Core:
    file: lib/Posy/Core.pm
    version: 0.10
  Posy::Plugin::BinFile:
    file: lib/Posy/Plugin/BinFile.pm
    version: 0.10
  Posy::Plugin::Canonical:
    file: lib/Posy/Plugin/Canonical.pm
    version: 0.10
  Posy::Plugin::Categories:
    file: lib/Posy/Plugin/Categories.pm
    version: 0.10
  Posy::Plugin::CgiCarp:
    file: lib/Posy/Plugin/CgiCarp.pm
    version: 0.10
  Posy::Plugin::Dump:
    file: lib/Posy/Plugin/Dump.pm
    version: 0.10
  Posy::Plugin::DynamicCss:
    file: lib/Posy/Plugin/DynamicCss.pm
    version: 0.10
  Posy::Plugin::EntryTitles:
    file: lib/Posy/Plugin/EntryTitles.pm
    version: 0.10
  Posy::Plugin::FileStats:
    file: lib/Posy/Plugin/FileStats.pm
    version: 0.10
  Posy::Plugin::FlavourMenu:
    file: lib/Posy/Plugin/FlavourMenu.pm
    version: 0.10
  Posy::Plugin::GenStatic:
    file: lib/Posy/Plugin/GenStatic.pm
    version: 0.10
  Posy::Plugin::LinkExtra:
    file: lib/Posy/Plugin/LinkExtra.pm
    version: 0.10
  Posy::Plugin::LinkList:
    file: lib/Posy/Plugin/LinkList.pm
    version: 0.10
  Posy::Plugin::LocalDepth:
    file: lib/Posy/Plugin/LocalDepth.pm
    version: 0.10
  Posy::Plugin::NearLinks:
    file: lib/Posy/Plugin/NearLinks.pm
    version: 0.10
  Posy::Plugin::RandQuote:
    file: lib/Posy/Plugin/RandQuote.pm
    version: 0.10
  Posy::Plugin::ShortBody:
    file: lib/Posy/Plugin/ShortBody.pm
    version: 0.10
  Posy::Plugin::TextTemplate:
    file: lib/Posy/Plugin/TextTemplate.pm
    version: 0.10
  Posy::Plugin::TextToHTML:
    file: lib/Posy/Plugin/TextToHTML.pm
    version: 0.10
  Posy::Plugin::ThemeCss:
    file: lib/Posy/Plugin/ThemeCss.pm
    version: 0.10
  Posy::Plugin::ThisFlavour:
    file: lib/Posy/Plugin/ThisFlavour.pm
    version: 0.10
  Posy::Plugin::Toc:
    file: lib/Posy/Plugin/Toc.pm
    version: 0.10
  Posy::Plugin::YamlConfig:
    file: lib/Posy/Plugin/YamlConfig.pm
    version: 0.10
generated_by: Module::Build version 0.2607
