--- #YAML:1.0
name: Posy
version: 0.95
author:
  - Kathryn Andersen
abstract: a website generator inspired by blosxom
license: perl
requires:
  CGI::Minimal: 0
  File::Copy: 0
  File::Find: 0
  File::Spec: 0
  File::stat: 0
  Getopt::ArgvFile: 1.09
  Getopt::Long: 2.34
  Pod::Usage: 0
  Storable: 0
build_requires:
  Test::More: 0
provides:
  Posy:
    file: lib/Posy.pm
    version: 0.95
  Posy::Core:
    file: lib/Posy/Core.pm
    version: 0.95
  Posy::Plugin::GenStatic:
    file: lib/Posy/Plugin/GenStatic.pm
    version: 0.95
generated_by: Module::Build version 0.261
